# Generated by Django 5.2.6 on 2025-09-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_customer_name_alter_entry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='goods',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
